[package]
name = "jsl-infer"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@segment.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
failure = "0.1"
jsl = "0.2.4"
json-pointer = "0.3"
rand = "0.6"
serde_json = "1.0"
